### ISSUE TITLE
Unable to install Stata package

### ISSUE THREAD

**Issue by leostimpfle** [chaisemartinPackages/did_multiplegt_stat#21]
Hello, when trying to install the Stata package with

    net install did_multiplegt_stat, from("https://raw.githubusercontent.com/chaisemartinPackages/did_multiplegt_stat/main/Stata") replace

I receive the following error:

    https://raw.githubusercontent.com/chaisemartinPackages/did_multiplegt_stat/main/Stata/ either
      1)  is not a valid URL, or
      2)  could not be contacted, or
      3)  is not a Stata download site (has no stata.toc file).

Is this expected?

Many thanks,
Leo

**Comment by romgoti** [comment]
Dear Leo,
Maybe you should use the SSC installation : 

```s
ssc install did_multiplegt_stat
```

It worked for me !
Best,
Romain

**Comment by DouloSOW** [comment]
Dear Leo, 
The problem is solved! 

Thanks
